# Default values for multi-container-app
replicaCount: 1

# Frontend configuration
frontend:
  image:
    repository: nginx
    tag: "1.19.10-alpine"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Backend configuration
backend:
  image:
    repository: node
    tag: "14-alpine"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

# Redis configuration
redis:
  enabled: true
  image:
    repository: redis
    tag: "6.2-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 6379
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# ServiceMonitor for Prometheus (requires Prometheus Operator)
serviceMonitor:
  enabled: false

# Ingress configuration (uncomment to enable)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
